### ISSUE TITLE
Uncertain if GH Actions supports additional matrix inputs

### ISSUE THREAD

**Issue by faxblaster** [tighten/phpreleases-action#1]
The hope was, we could end up doing something like this in the matrix, allowing users to layer in additional matrix inclusions as-needed.

```
    strategy:
      matrix: ${{ fromJSON(needs.output_releases.outputs.range) }}
          laravel: ['6.x', '8.x', '9.x']
          os: [Ubuntu, Windows, macOS]
```

 I spent a little bit of time trying this out myself, and it doesn't appear to be supported. I also found this note by a user on [Stack Overflow](https://stackoverflow.com/a/65094398): 
> This is the only way you can dynamically generate a matrix build, you have to provide all the combinations on your own using matrix.include.
